services:
  db:
    container_name: db-postgres-metrics
    hostname: postgres-metrics
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metrics
